# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create New Release

on:
  release:
    types: [created]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run install-react-mui
      - run: npm run build
      - run: npx jest --env=jsdom --config=jest.config.js --coverage --ci --updateSnapshot --detectOpenHandles --forceExit

  publish-npm:
    if: "!github.event.release.prerelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run install-react-mui
      - run: npm run build
      - run: npx tsc index.js --declaration --allowJs --emitDeclarationOnly --skipLibCheck --outDir .
      - run: npm install -g json
      - run: json -I -f package.json -e 'this.scripts.postinstall="echo done"'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    if: "!github.event.release.prerelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run install-react-mui
      - run: npm run build
      - run: npx tsc index.js --declaration --allowJs --emitDeclarationOnly --skipLibCheck --outDir .
      - run: npm install -g json
      - run: json -I -f package.json -e 'this.name="@vip-git/react-jsonschema-form-material-ui"'
      - run: json -I -f package.json -e 'this.scripts.postinstall="echo done"'
      - run: npm publish --registry=https://npm.pkg.github.com --scope=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
